# Generated by Django 6.0 on 2025-12-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metroline',
            name='ticket_purchase_enabled',
        ),
        migrations.RemoveField(
            model_name='station',
            name='metro_line',
        ),
        migrations.AddField(
            model_name='station',
            name='lines',
            field=models.ManyToManyField(related_name='stations', to='stations.metroline'),
        ),
    ]
